---
title: "CIDER"
execute: 
  echo: false
html-table-processing: none
---


```{r}
#| label: setup
source(here::here("_setup.R"))
tool <- "cider"
dat$data <- dat$data |>
  dplyr::filter(grepl(tool, .data$tool_parser))
dat$schemas <- dat$schemas |>
  dplyr::filter(.data$tool == {{ tool }})
```

## BLASTn hits

```{r}
#| label: blastn
tbl_nm <- "cider_blastn"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  tw_table$reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

## Locus stats

```{r}
#| label: cider_locstats
tbl_nm <- "cider_locstats"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  tw_table$reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

## VDJ sequences

```{r}
#| label: cider_vdj
tbl_nm <- "cider_vdj"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  tw_table$reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

::: {.callout-tip}
## TODO

- Do not wrap sequences in VDJ table
:::
