---
title: "PEACH"
execute: 
  echo: false
html-table-processing: none
---


```{r}
#| label: setup
source(here::here("_setup.R"))
use("gt", "gt")
tool <- "peach"
dat$data <- dat$data |>
  filter(grepl(tool, .data$tool_parser))
dat$schemas <- dat$schemas |>
  filter(.data$tool == {{ tool }})
```

## QC

```{r}
#| label: peach_qc
tbl_nm <- "peach_qc"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Variant events

```{r}
#| label: peach_events
tbl_nm <- "peach_events"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Variant events linked to gene

```{r}
#| label: peach_eventsg
tbl_nm <- "peach_eventsg"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Haplotypes (best)

```{r}
#| label: peach_hapbest
tbl_nm <- "peach_hapbest"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Haplotypes (all)

```{r}
#| label: peach_hapall
tbl_nm <- "peach_hapall"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

::: {.callout-tip}
## TODO

- Format tables better
:::
