---
title: "VIRUS"
execute: 
  echo: false
html-table-processing: none
---


```{r}
#| label: setup
source(here::here("_setup.R"))
tool <- "virus"
dat$data <- dat$data |>
  dplyr::filter(grepl(tool, .data$tool_parser))
dat$schemas <- dat$schemas |>
  dplyr::filter(grepl({{ tool }}, .data$tool))
```

## VIRUSBreakend analysis summary

```{r}
#| label: virusbreakend_summary
tbl_nm <- "virusbreakend_summary"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  tw_table$reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

## Virus Interpreter oncoviral call/annotation data

```{r}
#| label: virusinterpreter_annotated
tbl_nm <- "virusinterpreter_annotated"
d <- dat$data |>
  tw_utils$unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  tw_table$reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```


::: {.callout-tip}
## TODO

- Find viral test data
:::
